title: Fwordle Policies
description: Official policies for the Fwordle iOS app
baseurl: "/fwordle-policies"
url: "https://nigelware.github.io"
markdown: kramdown
permalink: pretty
collections:
  policies:
    output: true
